CREATE TABLE Categorie (
	id INTEGER NOT NULL UNIQUE,
	nom VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE Produit(
	id INTEGER NOT NULL UNIQUE,
	nom VARCHAR(40) NOT NULL,
	code  INTEGER NOT NULL UNIQUE,
	categorie_id INTEGER NOT NULL UNIQUE,
	PRIMARY KEY (id),
	
	CONSTRAINT produit_categorie_fk
		FOREIGN KEY (categorie_id) 
		REFERENCES Categorie(id)

);

